export interface AnyAction {
  type: string;
  payload?: any;
}

export const ActionTypes = {
  GET_MY_APPS: 'GET_MY_APPS',
  CREATE_APP: 'CREATE_APP',
  SET_MY_APPS: 'SET_APPS',
  LAUNCH_APP_HOSTING: 'LAUNCH_APP_HOSTING',
  SET_USER: 'SET_USER',
  CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',
  SET_APP_ERROR: 'SET_APP_ERROR',
  SET_APP_INFO: 'SET_APP_INFO',
  SET_APP_LOADING: 'SET_APP_LOADING',
  CONNECT_GITHUB: 'CONNECT_GITHUB',
  GET_GITHUB_REPOS: 'GET_GITHUB_REPOS',
  SET_GITHUB_REPOS: 'SET_GITHUB_REPOS',
  PATCH_USER: 'PATCH_USER',
  ADD_ENV_VARS: 'ADD_ENV_VARS',
  TERMINATE_HOSTING: 'TERMINATE_HOSTING',
  DELETE_APP: 'DELETE_APP',
  ADD_HTTPS_LISTENER: 'ADD_HTTPS_LISTENER',
  GET_CERTIFICATES: 'GET_CERTIFICATES',
  SET_CERTIFICATES: 'SET_CERTIFICATES',
  CREATE_CERTIFICATE: 'CREATE_CERTIFICATE',
  ADD_EC2_HTTPS_LISTENER: 'ADD_EC2_HTTPS_LISTENER',
};
